name: CI

on:
  push:
    branches: [main, master]

  pull_request:
    branches: [main, master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun ci

      - name: Typecheck domain and API
        run: bun run build:domain

      - name: Build API
        run: bun run build:api

      # - name: Build FrontEnd
      #   run: bun run build:web

      - name: Run unit tests
        run: bun test

        env:
          USE_MEMORY_DB: "true"
